name: Daily SDE Digest

on:
  schedule:
    - cron: "30 6 * * *"  # 12:00 IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          COMPANIES: ${{ secrets.COMPANIES }}
          ROLE_QUERY: ${{ secrets.ROLE_QUERY }}
          SITES_HINT: ${{ secrets.SITES_HINT }}
        run: python job_bot.py
